# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

source ~/completions/git-completions.bash

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
# if ! shopt -oq posix; then
#   if [ -f /usr/share/bash-completion/bash_completion ]; then
#     . /usr/share/bash-completion/bash_completion
#   elif [ -f /etc/bash_completion ]; then
#     . /etc/bash_completion
#   fi
# fi

# Homebrew sourcing
eval $(/opt/homebrew/bin/brew shellenv)

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Aliases
alias ds='docker ps'
alias gl='git log'
alias gd='git diff HEAD'
alias gs='git status'
alias ls='exa'
alias y='yarn'
alias yb='yarn build'
alias yl='yarn lint'
alias yt='yarn test'
alias yp='yarn prettier'
alias yr='yarn rebuild'
alias tmux="TERM=screen-256color-bce tmux"

# alacritty color change
function ac() {
    if [[ -z "$1" ]]
    then
        cat ~/alacritty/base.yml > ~/.config/alacritty/alacritty.yml
    else
        cat ~/alacritty/base.yml ~/alacritty/"$1".yml > ~/.config/alacritty/alacritty.yml
    fi
}

# Use node 20
nvm use 20

# Starship Initialization
eval "$(starship init bash)"

# Aliases

alias pip='pip3'
alias python='python3'
alias vim='nvim'

# Foundry

export PATH="$PATH:/Users/alextowle/.foundry/bin"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

. "$HOME/.local/bin/env"
