# Setting PATH for Python 3.6
# The original version is saved in .bash_profile.pysave
export PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"

# Add rust binary files to the path variable
export PATH="$HOME/.cargo/bin:$PATH"

# Set the GOPATH environment variable and the path variable to include the GOPATH's bin
export GOPATH="$HOME/go"
export PATH=$PATH:$GOPATH/bin

# Add this to your ~/.bash_profile file:
export NODE_PATH="/usr/local/lib/node_modules"

### Alias python2 to python3
alias python=python3

### Functions and Aliases ###

# A quick and dirty find and replace script on a given file.
function sid() {
    cat "$1" | sed "s/"$2"/"$3"/g" > temp
    mv temp "$1"
}

function beep() {
    printf "\a"
}

## emacs aliases ##

alias emacs=/Applications/Emacs.app/Contents/MacOS/Emacs

## cd aliases ##

alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'

function cd0x() {
    cd $(find_parent_that_matches "^0x-monorepo" $HOME)
}

## filesystem functions ##

### Uses the working directory path to derive the closest parent directory name that matches
### a regular expression.
### @param($1): This is the regex that should match the parent
### @param($2): This is the stop directory. This defaults to the / directory.
function find_parent_that_matches() {
    current_dir=$(pwd)
    match="$1"
    stop="$2"
    while [[ $current_dir != $stop ]]; do
        if [[ $(basename $current_dir) =~ $match ]]; then
            echo $current_dir
            break
        fi
        current_dir=$(dirname $current_dir)
    done
}

## vim ##

alias vimc='vim $CURRENT_FILE'

## git ##

function gc() {
    git add -A && git commit -m "$1"
}

function gcm() {
    git add -A && git commit -m "$1"
}

function vga() {
    vim "$1" && git add -A "$1"
}

## 0x ##

MAIN_BRANCH=3.0

function yc() {
    yarn clean
}

function yb() {
    yarn build
}

function yt() {
    yarn test
}

function yl() {
    yarn lint
}

function ybt() {
    yb && yt
}

function yall() {
    yc && yb && yt && yl
}

function ypall() {
    ybc && yt && yl && yp
}

function ybc() {
    old=$(pwd)
    parent=$(find_parent_that_matches "^0x-monorepo" $HOME)
    cd $parent
    yarn build:contracts
    cd $old
}

function ytc() {
    old=$(pwd)
    parent=$(find_parent_that_matches "^0x-monorepo" $HOME)
    cd $parent
    yarn test:contracts
    cd $old
}

function ylc() {
    old=$(pwd)
    parent=$(find_parent_that_matches "^0x-monorepo" $HOME)
    cd $parent
    yarn lint:contracts
    cd $old
}

function yp() {
    old=$(pwd)
    parent=$(find_parent_that_matches "^0x-monorepo" $HOME)
    cd $parent
    yarn prettier
    cd $old
}

function ycall() {
    ybc && ytc && ylc && yp
}

function refresh() {
    old=$(pwd)
    parent=$(find_parent_that_matches "^0x-monorepo" $HOME)
    cd $parent
    git checkout $MAIN_BRANCH
    git pull origin $MAIN_BRANCH
    yarn clean
    yarn
    yb
    ybc
    cd $old
}

## Rust Functions ##

function cb() {
    cargo build
}

function cc() {
    cargo check
}

function ct() {
    cargo test
}

function cbt() {
    cargo build && cargo test
}

## Setup for the "Node Version Manager" ##
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

## Enable Bash Powerline ##
source ~/.bash-powerline.sh

## Enable git completion for bash ##
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion || {
    # if not found in /usr/local/etc, try the brew --prefix location
    [ -f "$(brew --prefix)/etc/bash_completion.d/git-completion.bash" ] && \
        . $(brew --prefix)/etc/bash_completion.d/git-completion.bash
}
