set nocompatible

" These settings are required before calling vundle#begin()
filetype indent off
filetype plugin off
filetype plugin indent off

" Setup vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tomlion/vim-solidity'
Plugin 'scrooloose/nerdtree'
Plugin 'altercation/vim-colors-solarized'
Plugin 'https://github.com/rhysd/vim-wasm'
Plugin 'https://github.com/dense-analysis/ale'
Plugin 'tpope/vim-fugitive'
Plugin 'leafgarland/typescript-vim'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
Plugin 'https://github.com/Quramy/tsuquyomi'
Plugin 'https://github.com/vim-syntastic/syntastic'
Plugin 'fatih/vim-go'
call vundle#end()

" These settings are required after calling vundle#end()
filetype plugin indent on
syntax on

set number
set clipboard=unnamed
let g:solarized_termcolors=256
set background=dark
colorscheme solarized
set tabstop=4
set shiftwidth=4
set autoindent
set smartindent
set expandtab
imap jj <esc>
nmap <Down> <nop>
nmap <Up> <nop>
nmap <Left> <nop>
nmap <Right> <nop>
imap <Down> <nop>
imap <Up> <nop>
imap <Left> <nop>
imap <Right> <nop>
nmap - ddp

nnoremap [c gg<c-v>GI//<esc>
nnoremap [C gg<c-v>Gld
nnoremap [s :%s/\/\/.*//g<cr>

set colorcolumn=80

let extension = expand('%:e')
if extension == "cr"
  set filetype=ruby
endif

if extension == "c" || extension == "h"
  set tabstop=8
  set shiftwidth=8
  inoremap [u uint64_t
endif

if extension == 'go'
  set expandtab!
  set tabstop=8
  set shiftwidth=8
endif

nnoremap [js :set filetype=javascript<cr>
autocmd FileType bash,sh,vim,typescript,javascript,solidity,rust,go autocmd BufWritePre <buffer> %s/\s\+$//e
command! -complete=file -nargs=1 Rpdf :r !pdftotext -nopgbrk <q-args> - |fmt -csw78

" Syntastic
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_typescript_checkers = ['tsuquyomi'] " You shouldn't use 'tsc' checker.

" Ale Commands
let g:ale_linters = {
    \ 'go': ['gofmt'],
    \ 'typescript': ['tslint']
    \ }
let g:ale_fixers = {
    \ 'go': ['gofmt'],
    \ 'typescript': ['prettier']
    \ }
let g:ale_fix_on_save = 1
nnoremap ;a :ALENext<cr>
nnoremap ;b :ALELast<cr>
autocmd bufwritepost .vimrc source ~/.vimrc

" tsuquyomi
if extension == 'ts'
    noremap [d :TsuDef<cr>
    noremap [l <c-t>
    inoremap <c-n> <c-x><c-o>
    inoremap <c-p> <c-x><c-o>
endif
